name: Railway Scheduler

on:
  schedule:
    # Pause at 9 PM PST (05:00 UTC)
    - cron: "0 5 * * *"
    # Resume at 5 AM PST (13:00 UTC)
    - cron: "0 13 * * *"

jobs:
  pause-service:
    if: github.event.schedule == '0 5 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Authenticate with Railway
        run: railway login --token ${{ secrets.RAILWAY_TOKEN }}

      - name: Pause Service
        run: railway service pause 6479a5ac-eabe-40a4-bd92-ac123e0ccf39 --project d0d96ce4-a2b6-488e-b79d-5e8a34a89d03

  resume-service:
    if: github.event.schedule == '0 13 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Authenticate with Railway
        run: railway login --token ${{ secrets.RAILWAY_TOKEN }}

      - name: Resume Service
        run: railway service unpause 6479a5ac-eabe-40a4-bd92-ac123e0ccf39 --project d0d96ce4-a2b6-488e-b79d-5e8a34a89d03
